### ISSUE TITLE
c++ sdk detection for instance segmentation [Bug] 

### ISSUE THREAD

**Issue by GiovanniFyc** [open-mmlab/mmdeploy#2328]
### Checklist

- [ ] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/tree/main/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

when i use the c++ sdk detection for instance segmentation(by my dataset),the mask is none ,then i try the coco dataes,but the same,the model is rtmdet,the sample is c++ detection sample ,
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/1ba1ca16-8fad-4eb3-85fa-1556c3f47233)
save image has no mask,
deploy the model,get the follow img:
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/c96347c3-e6f8-43cc-832f-58892afdd2b0)
when use c++ sdk:
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/c94d8bc6-1e5c-4d00-a628-179564fb0433)
the c++ code:
`
#include <cstdlib>
#include <opencv2/opencv.hpp>
#include "mmdeploy/detector.hpp"
#include <chrono>
#include "visualize.h"

int main() {
  const char* device_name = "cpu";
  int device_id = 0;
  std::string model_path = "/home/a/mmdeploy_model/rtmdetins-s-onnx-gf";
  std::string image_path = "/home/a/mmdeploy/demo/resources/det.jpg";
   mmdeploy::Model model(model_path);
   mmdeploy::Detector detector(model, mmdeploy::Device{device_name, device_id});
   cv::Mat img = cv::imread(image_path);
     auto dets = detector.Apply(img);
//code det.mask seem none
  utils::Visualize v;
  auto sess = v.get_session(img);
  int count = 0;
  for (const mmdeploy_detection_t& det : dets) {
    if (det.score > 0.6) {  // filter bboxes
      sess.add_det(det.bbox, det.label_id, det.score, det.mask, count++);
    }
  }
  cv::imwrite("out.png", sess.get());
  return 0;
}
`

### Reproduction

c++,just run the given model pth.

### Environment

```Shell
08/05 13:06:11 - mmengine - INFO - **********Environmental information**********
/bin/sh: 1: /usr/local/cuda-11.4/bin/bin/nvcc: not found
/bin/sh: 1: /usr/local/cuda-11.4/bin/bin/nvcc: not found
08/05 13:06:12 - mmengine - INFO - sys.platform: linux
08/05 13:06:12 - mmengine - INFO - Python: 3.9.17 (main, Jul  5 2023, 20:41:20) [GCC 11.2.0]
08/05 13:06:12 - mmengine - INFO - CUDA available: True
08/05 13:06:12 - mmengine - INFO - numpy_random_seed: 2147483648
08/05 13:06:12 - mmengine - INFO - GPU 0: NVIDIA GeForce RTX 3090
08/05 13:06:12 - mmengine - INFO - CUDA_HOME: /usr/local/cuda-11.4/bin
08/05 13:06:12 - mmengine - INFO - NVCC: Not Available
08/05 13:06:12 - mmengine - INFO - GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
08/05 13:06:12 - mmengine - INFO - PyTorch: 1.12.1+cu116
08/05 13:06:12 - mmengine - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

08/05 13:06:12 - mmengine - INFO - TorchVision: 0.13.1+cu116
08/05 13:06:12 - mmengine - INFO - OpenCV: 4.8.0
08/05 13:06:12 - mmengine - INFO - MMEngine: 0.8.2
08/05 13:06:12 - mmengine - INFO - MMCV: 2.0.1
08/05 13:06:12 - mmengine - INFO - MMCV Compiler: GCC 9.3
08/05 13:06:12 - mmengine - INFO - MMCV CUDA Compiler: 11.6
08/05 13:06:12 - mmengine - INFO - MMDeploy: 1.2.0+92df991
08/05 13:06:12 - mmengine - INFO - 

08/05 13:06:12 - mmengine - INFO - **********Backend information**********
08/05 13:06:12 - mmengine - INFO - tensorrt:	8.4.2.4
08/05 13:06:12 - mmengine - INFO - tensorrt custom ops:	Available
08/05 13:06:12 - mmengine - INFO - ONNXRuntime:	1.15.1
08/05 13:06:12 - mmengine - INFO - ONNXRuntime-gpu:	1.15.1
08/05 13:06:12 - mmengine - INFO - ONNXRuntime custom ops:	Available
08/05 13:06:12 - mmengine - INFO - pplnn:	None
08/05 13:06:12 - mmengine - INFO - ncnn:	None
08/05 13:06:12 - mmengine - INFO - snpe:	None
08/05 13:06:12 - mmengine - INFO - openvino:	2023.0.1
08/05 13:06:12 - mmengine - INFO - torchscript:	1.12.1+cu116
08/05 13:06:12 - mmengine - INFO - torchscript custom ops:	NotAvailable
08/05 13:06:12 - mmengine - INFO - rknn-toolkit:	None
08/05 13:06:12 - mmengine - INFO - rknn-toolkit2:	None
08/05 13:06:12 - mmengine - INFO - ascend:	None
08/05 13:06:12 - mmengine - INFO - coreml:	None
08/05 13:06:12 - mmengine - INFO - tvm:	None
08/05 13:06:12 - mmengine - INFO - vacc:	None
08/05 13:06:12 - mmengine - INFO - 

08/05 13:06:12 - mmengine - INFO - **********Codebase information**********
08/05 13:06:12 - mmengine - INFO - mmdet:	3.1.0
08/05 13:06:12 - mmengine - INFO - mmseg:	None
08/05 13:06:12 - mmengine - INFO - mmpretrain:	None
08/05 13:06:12 - mmengine - INFO - mmocr:	None
08/05 13:06:12 - mmengine - INFO - mmagic:	None
08/05 13:06:12 - mmengine - INFO - mmdet3d:	None
08/05 13:06:12 - mmengine - INFO - mmpose:	None
08/05 13:06:12 - mmengine - INFO - mmrotate:	None
08/05 13:06:12 - mmengine - INFO - mmaction:	None
08/05 13:06:12 - mmengine - INFO - mmrazor:	None
08/05 13:06:12 - mmengine - INFO - mmyolo:	None
```

**Comment by fanyunchao** [comment]
python code:
`import argparse
import math

import cv2
from mmdeploy_runtime import Detector


def main():
    img = cv2.imread('/home/a/mmdeploy/demo/resources/1.png')
    detector = Detector(
        model_path='/home/a/mmdeploy/work_dirs/rtmdetins-s-onnx', device_name='cpu', device_id=0)
    bboxes, labels, masks = detector(img)

    indices = [i for i in range(len(bboxes))]
    for index, bbox, label_id in zip(indices, bboxes, labels):
        [left, top, right, bottom], score = bbox[0:4].astype(int), bbox[4]
        if score < 0.3:
            continue

        cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0))

        if masks[index].size:
            mask = masks[index]
            blue, green, red = cv2.split(img)

            x0 = int(max(math.floor(bbox[0]) - 1, 0))
            y0 = int(max(math.floor(bbox[1]) - 1, 0))
            mask_img = blue[y0:y0 + mask.shape[0], x0:x0 + mask.shape[1]]
            cv2.bitwise_or(mask, mask_img, mask_img)
            img = cv2.merge([blue, green, red])

    cv2.imwrite('output_detection.png', img)


if __name__ == '__main__':
    main()`
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/46a1da39-069e-4474-9d17-4279aaeb56aa)
i don't know what happend

**Comment by fanyunchao** [comment]
I have retrained the model and converted it into a Tensorrt model. Using C++SDK can perform inference normally, but there are still problems converting to ONNX for inference, and the mask cannot be obtained correctly. The problem may occur in the size of the transformed model. I am continuing to try some more.

**Comment by fanyunchao** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/df5007e6-7684-48b3-8b50-14c2d35f9af7)
right is tensorrt,right is onnx

**Comment by fanyunchao** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/6ad50991-a496-4612-ae23-f9a42362865f)
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/6ad7e1e7-78ef-419e-94d0-2cd150575b84)
i use the python code to infer the onnx model,different times get different result
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/a89b38a8-cf68-4f13-aa34-f51259cb7b82)

**Comment by fanyunchao** [comment]
i have already reinstall the mmdeploy and mmdection ,test for rtmdet instance segmentation,get same result,infer by onnx seem to be wrong.
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/3637e05f-5ca8-4be5-81da-2b17ad8e10be)
but in converting the model,the result seem to be true.
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/6d7dc2df-b86f-4f2a-8efc-edda141b6f96)

**Comment by fanyunchao** [comment]
i reinstall onnxruntime,tensorrt,pytorch,cuda,...,and retry ,infer by onnx get same wrong result

**Comment by RunningLeon** [comment]
Hi, sorry for the late reply. We'll reproduce the issue with the docker image. If there's any bug, will fix soon.

**Comment by fanyunchao** [comment]
I also tried using Docker to reproduce this issue. If you already have test results, could you please let me know and I will stop testing this issue

**Comment by RunningLeon** [comment]
> 

hi, we have reproduced the issue. Debugging is in progress.

**Comment by RunningLeon** [comment]
@GiovanniFyc hi, masks from RTMDet-Inst are already resized to the image shape, which have shape like `1xNxHxW`, so you have to crop it to origin_img_shape. Maybe you could try the following as a workaround?
https://github.com/open-mmlab/mmdeploy/blob/8a59bae42a7ed4c5d39a2e91e0a4d96cc795ef3d/demo/python/object_detection.py#L38-L44

to 
```
 mask = masks[index] 
 # crop masks
 h, w, _ = img.shape
 mask = mask[:h, :w]
 blue, green, red = cv2.split(img) 
  
 # x0 = int(max(math.floor(bbox[0]) - 1, 0)) 
 # y0 = int(max(math.floor(bbox[1]) - 1, 0)) 
 # mask_img = blue[y0:y0 + mask.shape[0], x0:x0 + mask.shape[1]] 
 mask_img = blue
 cv2.bitwise_or(mask, mask_img, mask_img) 
```

**Comment by GiovanniFyc** [comment]
the mask has already resized to padded shape ,but the mask should not be zero
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/27dae59a-284e-461c-9b6b-8ea4162a9036)

**Comment by RunningLeon** [comment]
mask area inside bbox are not zeros. note it is insance segmentation task.

**Comment by GiovanniFyc** [comment]
i try it many times, most got all zeros,

**Comment by RunningLeon** [comment]
tested on `rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e/` with batchsize=1, and the results are aligned
![image](https://github.com/open-mmlab/mmdeploy/assets/28671653/4aede116-76f0-4e91-958e-486ba7e2df6a)

**Comment by GiovanniFyc** [comment]
onnx? inconceivable！！！

**Comment by GiovanniFyc** [comment]
Can you share your test code？

**Comment by GiovanniFyc** [comment]
I just want to use the ONNX model to obtain images like your results

**Comment by RunningLeon** [comment]
> @GiovanniFyc hi, masks from RTMDet-Inst are already resized to the padded shape, which has a shape like `1xNxPad_HxPad_W`, so you have to crop it to origin_img_shape. Maybe you could try to change `demo/python/object_detection.py` according to the following as a workaround?
> 
> https://github.com/open-mmlab/mmdeploy/blob/8a59bae42a7ed4c5d39a2e91e0a4d96cc795ef3d/demo/python/object_detection.py#L38-L44
> 
> to
> 
> ```
>  mask = masks[index] 
>  # crop masks
>  h, w, _ = img.shape
>  mask = mask[:h, :w]
>  blue, green, red = cv2.split(img) 
>   
>  # x0 = int(max(math.floor(bbox[0]) - 1, 0)) 
>  # y0 = int(max(math.floor(bbox[1]) - 1, 0)) 
>  # mask_img = blue[y0:y0 + mask.shape[0], x0:x0 + mask.shape[1]] 
>  mask_img = blue
>  cv2.bitwise_or(mask, mask_img, mask_img) 
> ```

have you tried this?

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/42b2df35-79eb-45bf-98e6-e07289e13215)

**Comment by GiovanniFyc** [comment]
i change one clean computer,only do this work ,reinstall all,but get the wrong reslut ,but the mask not be zeros

**Comment by GiovanniFyc** [comment]
can you share the onnx model that you test good? i test by my computer

**Comment by GiovanniFyc** [comment]
`python tools/deploy.py configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py /home/ktr/mmdetection-main/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py checkpoints/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth demo/resources/det.jpg  --work-dir ./work_dirs/ins-s-onnx --device cpu --show --dump-info`

when you convert the onnx model, anything changed to original code?

**Comment by GiovanniFyc** [comment]
> tested on `rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e/` with batchsize=1, and the results are aligned ![image](https://user-images.githubusercontent.com/28671653/259368296-4aede116-76f0-4e91-958e-486ba7e2df6a.png)

how to set batchsize?

**Comment by RunningLeon** [comment]
@GiovanniFyc pls. try this branch https://github.com/RunningLeon/mmdeploy/tree/fix_rtmdet_inst
1. git pull the branch
2. rebuild mmdeploy
3. rerun deploy.py
```
python3 tools/deploy.py \
configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py \
../mmdetection/configs/rtmdet/rtmdet-ins_tiny_8xb32-300e_coco.py \
../mmdeploy_checkpoints/mmdet/rtmdetinst/rtmdet-ins_tiny_8xb32-300e_coco_20221130_151727-ec670f7e.pth \
../mmdetection/demo/demo.jpg \
--work-dir ./work-dirs/mmdet/rtmdet-inst/ort \
--device cpu \
--test-img tests/data/tiger.jpeg \
--dump-info
```
5. test sdk model with
 -  `python demo/python/object_detection.py cpu ./work-dirs/mmdet/rtmdet-inst/ort demo/resources/det.jpg`
 -  or `./build/bin/object_detection cpu ./work-dirs/mmdet/rtmdet-inst/ort demo/resources/det.jpg`

**Comment by GiovanniFyc** [comment]
i rebuild environment ,
`conda activate new environment`
`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113`
`pip install -U openmim`
`mim install mmengine`
`mim install "mmcv>=2.0.0rc2"`
`mim install mmdet`
`cd ${new_mmdeploy_path}`
`mkdir build && cd build`
`cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_BUILD_SDK=ON -DMMDEPLOY_BUILD_EXAMPLES=ON -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}`
`make -j8`
`make install`
`mim install -e .`
`cd ..`
`python tools/deploy.py configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py /home/ktr/mmdetection-main/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py checkpoints/rtmdet-ins_s_8xb32-300e_coco_20221121_212604-fdc5d7ec.pth demo/resources/det.jpg`
`python demo/python/object_detection.py cpu ./work_dirs/ins-s-onnx demo/resources/det.jpg`
i meet this error :No module named 'mmdeploy_runtime'?
i should pip install mmdeploy_runtime or other?

**Comment by GiovanniFyc** [comment]
i use the c++ code get the true result ,
![output_detection](https://github.com/open-mmlab/mmdeploy/assets/55267877/b5d2ac7a-35f9-4b57-9f51-4fdc53ae5d8d)

**Comment by RunningLeon** [comment]
> 

@GiovanniFyc hi, you could add the `mmdeploy_runtime.cpython-38m-x86_64-linux-gnu.so` to PYTHONPATH like `export PYTHONPATH=$(pwd)/build/lib:$PYTHONPATH`

**Comment by GiovanniFyc** [comment]
i get it,thank you @RunningLeon

**Comment by GiovanniFyc** [comment]
[mmdeploy] [error] [permute.cpp:15] The size of axes should be equal to src, 3 vs 2
@RunningLeon , when trained model for my dataset and  inference by onnx ,i get this error ,i don't know what's this   mean.

**Comment by RunningLeon** [comment]
@GiovanniFyc hi, there might be some problem with image shape H > W. Will update the PR if fixed.

**Comment by RunningLeon** [comment]
@GiovanniFyc hi could you try the latest change in the pr https://github.com/open-mmlab/mmdeploy/pull/2343?

**Comment by GiovanniFyc** [comment]
i don't know which code i can try,ha ha @RunningLeon

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/e8bf5e72-d8b3-4254-930d-7a2228b1912d)
i use this code get follow error
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/160d3154-34fb-4867-b56d-bdbd6dcbd208)
i change the code as follow:
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/bf817577-cb2f-4cf1-8537-dd6e046d0713)
get follow error :
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/ec505366-0bbd-4fdc-9414-ee002458c1f6)
input image size is 640*640,nothing change ,but get different,amazing

**Comment by GiovanniFyc** [comment]
i make some logs in detector.hpp and test the case when i get this error :   free(): invalid pointer Aborted (core dumped),

the c++ code can go into destruction function, in pipeline.cpp this ->mmdeploy_pipeline_destroy funtion get an error

**Comment by GiovanniFyc** [comment]
is there any bug? @RunningLeon

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/2eb25742-2e2a-4906-bb03-45f9b6427d88)
i use the same shape and type image as the model input,but get this error

**Comment by RunningLeon** [comment]
@GiovanniFyc hi, have you pull the latest code and rebuild mmdeploy?

**Comment by GiovanniFyc** [comment]
@RunningLeon test by this https://github.com/RunningLeon/mmdeploy

**Comment by RunningLeon** [comment]
hi, it's not merged, so try this branch https://github.com/RunningLeon/mmdeploy/tree/fix_rtmdet_inst
`git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git`
or git fetch in existing repo
``` 
git remote add tmp https://github.com/RunningLeon/mmdeploy.git
git fetch tmp fix_rtmdet_inst 
git checkout tmp/fix_rtmdet_inst 
```

**Comment by GiovanniFyc** [comment]
> ![image](https://user-images.githubusercontent.com/55267877/260642506-2eb25742-2e2a-4906-bb03-45f9b6427d88.png) i use the same shape and type image as the model input,but get this error @RunningLeon

get this problem also , @RunningLeon 
`git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git`
`mkdir build && cd build`
`/home/ktr/cmake-3.26.5-linux-x86_64/bin/cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_BUILD_SDK=ON -DMMDEPLOY_BUILD_EXAMPLES=ON -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON -DMMDEPLOY_BUILD_SDK_CSHARP_API=ON -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}`
`make -j8`
`make install`

`cd code/build`
`/home/ktr/cmake-3.26.5-linux-x86_64/bin/cmake .. -DMMDeploy_DIR=${MMDEPLOY_DIR}`
`make `
`./...`
get error also

**Comment by GiovanniFyc** [comment]
> @GiovanniFyc hi, have you pulled the latest code and rebuilt mmdeploy?

i am sure my test code has already merge the pr #2334

**Comment by GiovanniFyc** [comment]
there also have many problem , but i didn't have any time to test it,hope to solve it soon,thanks for @RunningLeon

**Comment by RunningLeon** [comment]
> > ![image](https://user-images.githubusercontent.com/55267877/260642506-2eb25742-2e2a-4906-bb03-45f9b6427d88.png) i use the same shape and type image as the model input,but get this error @RunningLeon
> 
> get this problem also , @RunningLeon `git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git` `mkdir build && cd build` `/home/ktr/cmake-3.26.5-linux-x86_64/bin/cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_BUILD_SDK=ON -DMMDEPLOY_BUILD_EXAMPLES=ON -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON -DMMDEPLOY_BUILD_SDK_CSHARP_API=ON -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}` `make -j8` `make install`
> 
> `cd code/build` `/home/ktr/cmake-3.26.5-linux-x86_64/bin/cmake .. -DMMDeploy_DIR=${MMDEPLOY_DIR}` `make ` `./...` get error also ![image](https://user-images.githubusercontent.com/55267877/260668771-20344b66-f3e1-4ff3-b110-97e652877f19.png)

@GiovanniFyc have you rerun `deploy.py` to get new `end2end.onnx`?

**Comment by RunningLeon** [comment]
> there also have many problem , but i didn't have any time to test it,hope to solve it soon,thanks for @RunningLeon

Could try after this commit: https://github.com/open-mmlab/mmdeploy/pull/2343/commits/146c15a6ceefc68272c4b61121ede074de269fbd

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/acd8f70d-4a2b-4fcc-ae41-54e961455474)


> > there also have many problem , but i didn't have any time to test it,hope to solve it soon,thanks for @RunningLeon
> 
> Could try after this commit: [146c15a](https://github.com/open-mmlab/mmdeploy/commit/146c15a6ceefc68272c4b61121ede074de269fbd)
`git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git`
`mkdirbuild && cd build` 
`/home/ktr/cmake-3.26.5-linux-x86_64/bin/cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_BUILD_SDK=ON -DMMDEPLOY_BUILD_EXAMPLES=ON -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON -DMMDEPLOY_BUILD_SDK_CSHARP_API=ON -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}`
`make -j8`
`make install`
`cd ..`
`mim install -e .`
`python tools/deploy.py configs/mmdet/instance-seg/instance-seg_rtmdet-ins_onnxruntime_static-640x640.py /home/ktr/mmdetection-main/configs/rtmdet/rtmdet-ins_s_8xb32-300e_coco.py checkpoints/epoch_50.pth demo/resources/sc1.jpg  --work-dir ./work_dirs/ins-s-onnx --device cpu --show --dump-info`
get error 
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/4a0f7405-a6cc-43c2-94a7-7fb07f32eba7)

![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/9b0bcd9d-37a0-464d-876f-e84a89c772ca)

**Comment by GiovanniFyc** [comment]
anything change ?

**Comment by RunningLeon** [comment]
pls. try the latest code from pr https://github.com/open-mmlab/mmdeploy/issues/2334 in this branch https://github.com/RunningLeon/mmdeploy/tree/fix_rtmdet_inst

**Comment by gachiemchiep** [comment]
Hey @GiovanniFyc   @RunningLeon 

somehow when exporting model configuration, the *is_resize_mask* parameter that is used to  enable mask resizing is written as false. when deploying this parameter is true so when deploying the model, output will be right. But using demo to test your image, output will be wrong.   

```bash
# mmdeploy/csrc/mmdeploy/codebase/mmdet/instance_segmentation.cpp
      mask.Reshape({1, mask_height, mask_width, 1});
      if (is_resize_mask_) {
        auto& bbox = det.bbox;
        // same as mmdet with skip_empty = True

# mmdeploy/codebase/mmdet/deploy/object_detection_model.py
                # avoid to resize masks with zero dim
                if export_postprocess_mask and rescale and masks.shape[0] != 0:
                    masks = F.interpolate(
                        masks.unsqueeze(0),
                        size=[
                            math.ceil(masks.shape[-2] / scale_factor[0][0]),
                            math.ceil(masks.shape[-1] / scale_factor[0][1])
                        ])[..., :ori_h, :ori_w]
                    masks = masks.squeeze(0)
```

you need to edit the pipeline.json 

```bash
          "component": "ResizeInstanceMask",
                "params": {
                    "mask_thr_binary": 0.5,
                    "max_per_img": 100,
                    "min_bbox_size": 0,
                    "nms": {
                        "iou_threshold": 0.6,
                        "type": "nms"
                    },
                    "nms_pre": 1000,
                    "score_thr": 0.05,
                    "is_resize_mask": true          <----- this one should be false, turn into true
```

I test and it fixed the problem for both python and cpp demo. 

```bash
# cpp 
(openmmlab) gachiemchiep:mmdeploy$ ./build/bin/object_detection cuda work_dirs/rtmdet-ins_s_8xb32-300e_coco/tensorrt demo/frisk_003481.jpg
# output is like this
[2023-08-26 22:18:16.416] [mmdeploy] [info] [model.cpp:35] [DirectoryModel] Load model: "/datadrive/workspace/work_dirs/rtmdet-ins_s_8xb32-300e_coco/tensorrt"
bbox_count=5
box 0, left=155.83, top=655.76, right=502.50, bottom=863.10, label=3, score=0.9778
mask 0, height=211, width=350
box 1, left=174.88, top=382.58, right=516.35, bottom=559.91, label=2, score=0.9776
mask 1, height=180, width=345
box 2, left=143.75, top=75.69, right=498.12, bottom=298.71, label=1, score=0.9704
mask 2, height=226, width=358
box 3, left=173.92, top=381.18, right=518.20, bottom=559.15, label=3, score=0.0543
box 4, left=591.04, top=746.23, right=754.56, bottom=877.62, label=0, score=0.0538
```

and the instance segmentation result is like this 
![output_detection](https://github.com/open-mmlab/mmdeploy/assets/2300329/7f7e8d26-24ae-47af-abc6-45cf77d78509)

**Comment by RunningLeon** [comment]
@gachiemchiep hi, thanks for your info. The bug has been fixed in this PR https://github.com/open-mmlab/mmdeploy/pull/2343

**Comment by GiovanniFyc** [comment]
@RunningLeon i've been too busy to test lately,will test for it soon,thank you

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/733c9ece-4eca-43d0-8d97-972ffc991a25)
`mkdir build && cd build`
`cmake .. -DCMAKE_CXX_COMPILER=g++-7 -DMMDEPLOY_BUILD_SDK=ON -DMMDEPLOY_BUILD_EXAMPLES=ON -DMMDEPLOY_BUILD_SDK_PYTHON_API=ON -DMMDEPLOY_TARGET_DEVICES=cpu -DMMDEPLOY_TARGET_BACKENDS=ort -DONNXRUNTIME_DIR=${ONNXRUNTIME_DIR}`
`make -j8`
get this error

**Comment by GiovanniFyc** [comment]
![image](https://github.com/open-mmlab/mmdeploy/assets/55267877/1a8c0f38-8436-4960-b9f9-0f4a07f7f4e5)

**Comment by RunningLeon** [comment]
hi, pls. upgrade opencv if possible. Tested ok on opencv==4.2.0

**Comment by RunningLeon** [comment]
hi, https://github.com/open-mmlab/mmdeploy/issues/2334 is not merged. You should clone it and build from source.
`git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git`

**Comment by GiovanniFyc** [comment]
the sample of mmdeploy-main is true,but in convert has some problem,may be my mistake

**Comment by RunningLeon** [comment]
@GiovanniFyc hi, could use docker image and put all command in a bash script so we can reproduce? This PR tested ok on my local machine.

**Comment by GiovanniFyc** [comment]
我可以提供我训练的模型和测试图片，如果在你的机器上转换并运行正常，那就说明我的测试存在问题，我需要重新来测试他

**Comment by GiovanniFyc** [comment]
there is no bug for me in convert model to onnx after your commits yesterday , @RunningLeon  ,this error have already fix

> the sample of mmdeploy-main is true,but in convert has some problem,may be my mistake,will test for it.
> 
> > hi, #2334 is not merged. You should clone it and build from source. `git clone --recursive -b fix_rtmdet_inst https://github.com/RunningLeon/mmdeploy.git`
> 
> test for #2334 get error ![image](https://user-images.githubusercontent.com/55267877/263884395-d163f05b-2a57-4111-913b-a1f089d39fbe.png) convert get error

**Comment by RunningLeon** [comment]
hi, good to know. Actually, the error has been fixed many days ago in my PR. Yestoday, I just rebased my code with the latest main branch from mmdeploy.

**Comment by GiovanniFyc** [comment]
> hi, good to know. Actually, the error has been fixed many days ago in my PR. Yestoday, I just rebased my code with the latest main branch from mmdeploy.

test for your PR as the same as test for main,but different result,don't know what happen ,thanks for fix the bug

**Comment by LuukvandenBent** [comment]
Hi this issue still persists for me in the latest versions. 

2023-11-28:11:00:01 - root - ERROR - The shape of the mask [100] at index 0 does not match the shape of the indexed tensor [99, 640, 640] at index 0
Traceback (most recent call last):
  File "/root/workspace/mmdeploy/mmdeploy/utils/utils.py", line 41, in target_wrapper
    result = target(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/apis/visualize.py", line 72, in visualize_model
    result = model.test_step(model_inputs)[0]
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 299, in forward
    self.postprocessing_results(batch_dets, batch_labels, batch_masks,
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 189, in postprocessing_results
    outputs = End2EndModel.__clear_outputs(tmp_outputs)
  File "/root/workspace/mmdeploy/mmdeploy/codebase/mmdet/deploy/object_detection_model.py", line 104, in __clear_outputs
    outputs[2][i] = test_outputs[2][i, inds, ...]
IndexError: The shape of the mask [100] at index 0 does not match the shape of the indexed tensor [99, 640, 640] at index 0
11/28 11:00:02 - mmengine - ERROR - tools/deploy.py - create_process - 82 - visualize onnxruntime model failed.

I am running on docker image: [ubuntu20.04-cuda11.8-mmdeploy](https://hub.docker.com/layers/openmmlab/mmdeploy/ubuntu20.04-cuda11.8-mmdeploy/images/sha256-f2b90730c5e1b2b03b775bc592b8375af1daebb1d4ff80f5bff1594073fd0524?context=explore) and have pulled the latest updates and rebuild.

**Comment by RunningLeon** [comment]
@LuukvandenBent hi, pls. provide your steps to reproduce.

**Comment by JackIRose** [comment]
> > hi, good to know. Actually, the error has been fixed many days ago in my PR. Yestoday, I just rebased my code with the latest main branch from mmdeploy.
> 
> test for your PR as the same as test for main,but different result,don't know what happen ,thanks for fix the bug

你好，我遇到一个问题，使用python deploy.py进行一步转换的时候能够获取tensorRT engine模型，但使用C++推理时会提示我安装插件库，我看见你能够正常使用C++推理，这方面您是怎么操作的
